"""Human-readable names for linter/scanner rule codes."""

RULE_NAMES: dict[str, str] = {
    # ── Bandit (B*) ──
    "B101": "Assert Used",
    "B102": "Exec Used",
    "B103": "Bad File Permissions",
    "B104": "Hardcoded Bind All",
    "B105": "Hardcoded Password String",
    "B106": "Hardcoded Password Argument",
    "B107": "Hardcoded Password Default",
    "B108": "Hardcoded Temp File",
    "B110": "Try-Except-Pass",
    "B112": "Try-Except-Continue",
    "B113": "Request Without Timeout",
    "B301": "Pickle Deserialization",
    "B302": "Marshal Deserialization",
    "B303": "Insecure Hash (MD5/SHA1)",
    "B304": "Insecure Cipher",
    "B305": "Insecure Cipher Mode",
    "B306": "Temp File (mktemp)",
    "B307": "Eval Used",
    "B308": "Mark Safe (XSS Risk)",
    "B310": "URL Open (SSRF Risk)",
    "B311": "Random (Not Cryptographic)",
    "B312": "Telnet Usage",
    "B313": "XML Parse Vulnerable",
    "B314": "XML Parse Vulnerable",
    "B315": "XML Parse Vulnerable",
    "B316": "XML Parse Vulnerable",
    "B317": "XML Parse Vulnerable",
    "B318": "XML Parse Vulnerable",
    "B319": "XML Parse Vulnerable",
    "B320": "XML Parse Vulnerable",
    "B321": "FTP Usage",
    "B323": "Unverified SSL Context",
    "B324": "Insecure Hash Function",
    "B501": "No Certificate Validation",
    "B502": "SSL Bad Version",
    "B503": "SSL Bad Defaults",
    "B504": "SSL No Verify",
    "B505": "Weak Cryptographic Key",
    "B506": "Unsafe YAML Load",
    "B507": "Missing Host Key Verification",
    "B601": "Shell Injection (paramiko)",
    "B602": "Subprocess Shell=True",
    "B603": "Subprocess Without Shell",
    "B604": "Function Call Shell=True",
    "B605": "Start Process With Shell",
    "B606": "OS System Call",
    "B607": "Partial Path in Start Process",
    "B608": "SQL Injection (String Format)",
    "B609": "Wildcard Injection",
    "B610": "Django Extra Used",
    "B611": "Django Raw SQL Used",
    "B701": "Jinja2 Autoescape Off",
    "B702": "Mako Templates (XSS)",
    "B703": "Django Mark Safe",
    # ── Ruff / Pycodestyle (E*, W*, F*) ──
    "E101": "Mixed Indentation",
    "E111": "Bad Indentation",
    "E114": "Bad Indentation (Comment)",
    "E117": "Over-Indented",
    "E121": "Continuation Indentation",
    "E122": "Missing Indentation",
    "E125": "Continuation Indent",
    "E126": "Continuation Over-Indented",
    "E127": "Continuation Over-Indented",
    "E128": "Continuation Under-Indented",
    "E129": "Visually Indented",
    "E131": "Continuation Unaligned",
    "E133": "Closing Bracket Misaligned",
    "E201": "Whitespace After '('",
    "E202": "Whitespace Before ')'",
    "E211": "Whitespace Before '('",
    "E221": "Multiple Spaces Before Operator",
    "E222": "Multiple Spaces After Operator",
    "E225": "Missing Whitespace Around Operator",
    "E226": "Missing Whitespace Around Arithmetic",
    "E231": "Missing Whitespace After ','",
    "E241": "Multiple Spaces After ','",
    "E251": "Unexpected Spaces Around '='",
    "E252": "Missing Whitespace Around Default",
    "E261": "At Least Two Spaces Before Comment",
    "E262": "Inline Comment Should Start With '#'",
    "E265": "Block Comment Should Start With '# '",
    "E266": "Too Many '#' for Block Comment",
    "E271": "Multiple Spaces After Keyword",
    "E275": "Missing Whitespace After Keyword",
    "E301": "Expected Blank Lines",
    "E302": "Expected 2 Blank Lines",
    "E303": "Too Many Blank Lines",
    "E304": "Def After Decorator Has Blank Lines",
    "E401": "Multiple Imports On One Line",
    "E402": "Module Level Import Not At Top",
    "E501": "Line Too Long",
    "E502": "Backslash Is Redundant",
    "E701": "Multiple Statements On One Line (Colon)",
    "E711": "Comparison To None",
    "E712": "Comparison To True/False",
    "E713": "Not-In Test",
    "E714": "Not-Is Test",
    "E721": "Type Comparison Instead Of isinstance()",
    "E722": "Bare Except",
    "E731": "Lambda Assignment",
    "E741": "Ambiguous Variable Name",
    "E743": "Ambiguous Function Name",
    "E902": "Syntax/IOError",
    "E999": "Syntax Error",
    "W191": "Indentation Contains Tabs",
    "W291": "Trailing Whitespace",
    "W292": "No Newline At End Of File",
    "W293": "Whitespace Before ':'",
    "W391": "Blank Line At End Of File",
    "W503": "Line Break Before Binary Operator",
    "W504": "Line Break After Binary Operator",
    "W505": "Doc Line Too Long",
    # ── Pyflakes (F*) ──
    "F401": "Unused Import",
    "F402": "Import Shadowed By Loop",
    "F403": "Wildcard Import Used",
    "F405": "May Be Undefined From Wildcard",
    "F501": "Invalid % Format",
    "F502": "Expected %-Mapping Not Tuple",
    "F503": "Expected %-Tuple Not Mapping",
    "F504": "%-Format Unused Named Args",
    "F505": "%-Format Missing Named Args",
    "F506": "%-Format Mixed Positional/Named",
    "F507": "%-Format Mismatched Arg Count",
    "F508": "% On Non-String",
    "F509": "%-Format With * Specifier",
    "F521": "Invalid .format() String",
    "F522": ".format() Unused Named Args",
    "F523": ".format() Missing Named Args",
    "F524": ".format() Mixing Auto/Manual Numbering",
    "F525": ".format() Invalid Format",
    "F601": "Membership Test On List",
    "F602": "Membership Test On Tuple",
    "F621": "Too Many Expressions In Star",
    "F622": "Two+ Starred Expressions In Assignment",
    "F631": "Assert Test Is Tuple (Always True)",
    "F632": "Use == Instead Of is",
    "F633": "Use of __ne__ Instead Of __eq__",
    "F634": "Assert/Try After Return/Continue/Break",
    "F701": "Syntax Error In Type Comment",
    "F702": "Syntax Error In Type Comment",
    "F704": "Yield Outside Function",
    "F706": "Return Outside Function",
    "F707": "Except Has Invalid Syntax",
    "F811": "Redefined Unused Name",
    "F821": "Undefined Name",
    "F822": "Undefined Name In __all__",
    "F823": "Undefined Local With Import Star",
    "F841": "Unused Local Variable",
    "F842": "Unused Annotation",
    "F901": "Raise Not Implemented (Use NotImplementedError)",
    # ── Bugbear (B0*) ──
    "B002": "Unary Prefix Increment",
    "B003": "Assigning To os.environ (Use setdefault)",
    "B004": "Using hasattr() With __call__",
    "B005": "Strip With Multi-Char",
    "B006": "Mutable Default Argument",
    "B007": "Unused Loop Variable",
    "B008": "Function Call In Default Arg",
    "B009": "getattr With Constant",
    "B010": "setattr With Constant",
    "B011": "Assert False (Use raise)",
    "B012": "Return In finally",
    "B013": "Redundant Tuple In Exception",
    "B014": "Redundant Exception Types",
    "B015": "Useless Comparison",
    "B016": "Raise Literal",
    "B017": "assertRaises(Exception)",
    "B018": "Useless Expression",
    "B019": "functools.lru_cache On Methods",
    "B020": "Loop Variable Overrides Iterator",
    "B023": "Function Uses Loop Variable",
    "B024": "Abstract Class Without Abstract Methods",
    "B025": "Try-Except-Pass Duplicate",
    "B026": "Star-Arg Unpacking After Keyword",
    "B028": "No Explicit stacklevel In warnings",
    "B029": "Except Empty",
    "B030": "Except Duplicate Handlers",
    "B031": "Reuse Of groupby() Generator",
    "B032": "Unintentional Type Annotation",
    "B033": "Set Duplicate Item",
    "B034": "re.sub Without flags Arg",
    "B035": "Dict Duplicate Key In Comprehension",
    "B039": "ContextVar With Mutable Default",
    "B904": "Raise Without From In Except",
    "B905": "zip() Without strict=",
    # ── isort (I*) ──
    "I001": "Unsorted/Unformatted Imports",
    "I002": "Missing Required Import",
    # ── Naming (N*) ──
    "N801": "Class Name Not CapWords",
    "N802": "Function Name Not Lowercase",
    "N803": "Argument Name Not Lowercase",
    "N804": "First Argument Not cls",
    "N805": "First Argument Not self",
    "N806": "Variable Not Lowercase In Function",
    "N807": "Function Name Starts/Ends With __",
    "N811": "Constant Imported As Non-Constant",
    "N812": "Lowercase Imported As Non-Lowercase",
    "N813": "CamelCase Imported As Lowercase",
    "N814": "CamelCase Imported As Constant",
    "N815": "Variable mixedCase In Class",
    "N816": "Variable mixedCase In Module",
    "N817": "CamelCase Imported As Acronym",
    "N818": "Exception Name Not Error Suffix",
    "N999": "Invalid Module Name",
    # ── Annotations (ANN*) ──
    "ANN001": "Missing Function Arg Type",
    "ANN002": "Missing *args Type",
    "ANN003": "Missing **kwargs Type",
    "ANN101": "Missing Self Type",
    "ANN102": "Missing cls Type",
    "ANN201": "Missing Return Type",
    "ANN202": "Missing Return Type (Private)",
    "ANN204": "Missing Return Type (__init__)",
    "ANN205": "Missing Return Type (Magic)",
    "ANN206": "Missing Return Type (classmethod)",
    "ANN401": "Dynamically Typed (typing.Any)",
    # ── Docstrings (D*) ──
    "D100": "Missing Module Docstring",
    "D101": "Missing Class Docstring",
    "D102": "Missing Method Docstring",
    "D103": "Missing Function Docstring",
    "D104": "Missing Package Docstring",
    "D105": "Missing Magic Method Docstring",
    "D107": "Missing __init__ Docstring",
    "D200": "One-Line Docstring On Wrong Line",
    "D201": "No Blank Line Before Docstring",
    "D202": "No Blank Line After Docstring",
    "D205": "Blank Line Between Summary And Description",
    "D208": "No Over-Indented Docstring",
    "D209": "Closing Quotes On New Line",
    "D210": "No Whitespace Around Docstring",
    "D211": "No Blank Line Before Class Docstring",
    "D212": "Multi-Line Summary First Line",
    "D213": "Multi-Line Summary Second Line",
    "D300": "Use Triple Double Quotes",
    "D400": "First Line Should End With Period",
    "D401": "First Line Should Be Imperative",
    "D402": "First Line Should Not Be Function Sig",
    "D403": "First Word Of First Line Should Be Capital",
    "D404": "First Word Of Docstring Not 'This'",
    "D405": "Section Name Should Be Properly Capitalized",
    "D414": "Section Has No Content",
    "D415": "First Line Should End With Period/Question/Exclamation",
    "D417": "Missing Argument Descriptions",
    "D418": "@overload Should Not Have Docstring",
    "D419": "Non-Empty Docstring",
    # ── Security (S*) ──
    "S101": "Assert Used",
    "S102": "Exec Used",
    "S103": "Bad File Permissions",
    "S104": "Hardcoded Bind All",
    "S105": "Hardcoded Password String",
    "S106": "Hardcoded Password Argument",
    "S107": "Hardcoded Password Default",
    "S108": "Hardcoded Temp File",
    "S110": "Try-Except-Pass",
    "S113": "Request Without Timeout",
    "S301": "Pickle Deserialization",
    "S303": "Insecure Hash (MD5/SHA1)",
    "S307": "Eval Used",
    "S311": "Random (Not Cryptographic)",
    "S324": "Insecure Hash Function",
    "S501": "No Certificate Validation",
    "S506": "Unsafe YAML Load",
    "S602": "Subprocess Shell=True",
    "S603": "Subprocess Without Shell",
    "S605": "Start Process With Shell",
    "S607": "Partial Path in Start Process",
    "S608": "SQL Injection (String Format)",
    "S701": "Jinja2 Autoescape Off",
    # ── Simplify (SIM*) ──
    "SIM101": "Duplicate isinstance() Call",
    "SIM102": "Collapsible If Statements",
    "SIM103": "Return Boolean Directly",
    "SIM105": "Use contextlib.suppress()",
    "SIM107": "Return In Try/Except/Finally",
    "SIM108": "Use Ternary Operator",
    "SIM109": "Compare With Tuple Instead Of Or",
    "SIM110": "Use any() Instead Of For Loop",
    "SIM112": "Use os.environ Instead Of getenv",
    "SIM114": "Combine If Branches",
    "SIM115": "Use context manager For open()",
    "SIM116": "Use Dict Instead Of If/Elif",
    "SIM117": "Merge With Statements",
    "SIM118": "Use key in dict",
    "SIM201": "Use != Instead Of not ==",
    "SIM208": "Use Not Instead Of Double Negation",
    "SIM210": "Remove Unnecessary bool()",
    "SIM211": "Remove Unnecessary not",
    "SIM212": "Use Ternary Directly",
    "SIM220": "Expr Is Always False (a and not a)",
    "SIM221": "Expr Is Always True (a or not a)",
    "SIM222": "Use True Instead Of Or",
    "SIM223": "Use False Instead Of And",
    "SIM300": "Yoda Condition",
    "SIM401": "Use dict.get()",
    "SIM910": "Use dict.get() With Default",
    "SIM911": "Use zip() Instead Of enumerate+index",
    # ── Return (RET*) ──
    "RET501": "Unnecessary return None",
    "RET502": "Implicit return None",
    "RET503": "Missing Explicit return",
    "RET504": "Unnecessary Assignment Before return",
    "RET505": "Unnecessary else After return",
    "RET506": "Unnecessary else After raise",
    "RET507": "Unnecessary else After continue",
    "RET508": "Unnecessary else After break",
    # ── Upgrade (UP*) ──
    "UP001": "Useless Metaclass Type",
    "UP003": "Use type() Instead Of __class__",
    "UP004": "Useless Object Inheritance",
    "UP005": "Use typing Instead Of deprecated alias",
    "UP006": "Use type Instead Of typing.Type",
    "UP007": "Use X | Y Instead Of Union",
    "UP008": "Use super() Instead Of super(__class__)",
    "UP009": "UTF-8 Encoding Declaration",
    "UP010": "Unnecessary __future__ Import",
    "UP011": "Unnecessary lru_cache Parens",
    "UP012": "Unnecessary UTF-8 Encoding",
    "UP013": "Use class Instead Of TypedDict Call",
    "UP014": "Use class Instead Of NamedTuple Call",
    "UP015": "Unnecessary open Mode",
    "UP017": "Use datetime.UTC",
    "UP018": "Unnecessary Literal Call",
    "UP019": "Use typing.TypeAlias",
    "UP020": "Use typing.TypeAlias (3.9+)",
    "UP024": "Use aliased Exception",
    "UP025": "Use str.removeprefix/removesuffix",
    "UP026": "Use mock From unittest.mock",
    "UP027": "Unpacked List Comprehension",
    "UP028": "Use yield from",
    "UP029": "Unnecessary Default Type Args",
    "UP030": "Use Implicit Format Spec",
    "UP031": "Use Format Specifiers",
    "UP032": "Use f-string",
    "UP033": "Use @functools.cache",
    "UP034": "Unnecessary Parentheses After Class Def",
    "UP035": "Use PEP 585 Generics",
    "UP036": "Use PEP 604 Union",
    "UP037": "Use PEP 604 Optional",
    "UP038": "Use isinstance() With Union",
    "UP039": "Unnecessary Parentheses In Class",
    "UP040": "Use PEP 695 TypeAlias",
    # ── Ruff-specific (RUF*) ──
    "RUF001": "Ambiguous Unicode (String)",
    "RUF002": "Ambiguous Unicode (Docstring)",
    "RUF003": "Ambiguous Unicode (Comment)",
    "RUF005": "Unpack Instead Of Concatenate",
    "RUF006": "asyncio.create_task Missing Reference",
    "RUF007": "Use itertools.pairwise()",
    "RUF008": "Mutable ClassVar Default",
    "RUF009": "Mutable Dataclass Default",
    "RUF010": "Explicit f-string Type Conversion",
    "RUF012": "Mutable ClassVar Annotation",
    "RUF013": "Implicit Optional",
    "RUF015": "Prefer next() Over [0]",
    "RUF016": "Invalid Index Type",
    "RUF017": "Use math.isnan()",
    "RUF019": "Unnecessary Key Check Before Access",
    "RUF020": "Union Includes Never",
    "RUF100": "Unused noqa Directive",
    # ── Logging (G*) ──
    "G001": "Logging .format() String",
    "G002": "Logging % String",
    "G003": "Logging + String",
    "G004": "Logging f-string",
    "G010": "warn() Deprecated (Use warning())",
    "G101": "Logging Extra Arg",
    "G201": "Logging .exception() In except",
    "G202": "Logging Redundant exc_info",
    # ── Pylint (by message_id) ──
    "C0114": "Missing Module Docstring",
    "C0115": "Missing Class Docstring",
    "C0116": "Missing Function Docstring",
    "C0301": "Line Too Long",
    "C0302": "Too Many Lines In Module",
    "C0303": "Trailing Whitespace",
    "C0304": "Missing Final Newline",
    "C0321": "Multiple Statements On One Line",
    "C0325": "Unnecessary Parens After Keyword",
    "C0410": "Multiple Imports",
    "C0411": "Wrong Import Order",
    "C0412": "Ungrouped Imports",
    "C0413": "Import Not At Top",
    "C0414": "Useless Import Alias",
    "C0415": "Import Outside Top Level",
    "C2001": "Consider Using f-string",
    "E0001": "Syntax Error",
    "E0100": "Init Returns Non-None",
    "E0101": "Return In __init__",
    "E0102": "Function Already Defined",
    "E0103": "Not In Loop",
    "E0104": "Return Outside Function",
    "E0105": "Yield Outside Function",
    "E0107": "Non-Existent Operator",
    "E0108": "Duplicate Argument",
    "E0110": "Abstract Class With __init__",
    "E0111": "Reversed Dict/Set",
    "E0112": "Too Many Star Expressions",
    "E0115": "Nonlocal Without Binding",
    "E0116": "Continue In Finally",
    "E0117": "Nonlocal At Module Level",
    "E0118": "Name Used Prior To Global/Nonlocal",
    "E0211": "Method Has No Argument",
    "E0213": "Method Should Have 'self'",
    "E0237": "Assigning Non-Slot",
    "E0241": "Duplicate Base Class",
    "E0301": "Non-Iterator __next__",
    "E0302": "Unexpected Special Method Signature",
    "E0303": "Invalid __len__ Return",
    "E0401": "Import Error",
    "E0601": "Used Before Assignment",
    "E0602": "Undefined Variable",
    "E0611": "No Name In Module",
    "E0633": "Unpacking Non-Sequence",
    "E0701": "Bad Except Order",
    "E0702": "Raising Bad Type",
    "E0710": "Raising Non-Exception",
    "E0711": "Not Implemented Raised",
    "E0712": "Catching Non-Exception",
    "E1101": "No Member",
    "E1102": "Not Callable",
    "E1111": "Assignment From No Return",
    "E1120": "No Value For Parameter",
    "E1121": "Too Many Function Args",
    "E1123": "Unexpected Keyword Arg",
    "E1124": "Redundant Keyword Arg",
    "E1125": "Missing Kwonly Arg",
    "E1126": "Invalid Sequence Index",
    "E1127": "Invalid Slice Index",
    "E1128": "Invalid Slice Step",
    "E1129": "Not Context Manager",
    "E1130": "Invalid Unary Operand Type",
    "E1131": "Unsupported Binary Operation",
    "E1132": "Repeated Keyword",
    "E1133": "Non-Iterable Value",
    "E1134": "Non-Mapping Value",
    "E1135": "Unsupported Membership Test",
    "E1136": "Unsubscriptable Object",
    "E1137": "Unsupported Assignment",
    "E1138": "Unsupported Delete",
    "E1139": "Invalid Metaclass",
    "E1140": "Unhashable Member",
    "E1141": "Dict Item Not Iterable",
    "E1142": "Await Outside Async",
    "R0801": "Duplicate Code",
    "R0901": "Too Many Ancestors",
    "R0902": "Too Many Instance Attributes",
    "R0903": "Too Few Public Methods",
    "R0904": "Too Many Public Methods",
    "R0911": "Too Many Return Statements",
    "R0912": "Too Many Branches",
    "R0913": "Too Many Arguments",
    "R0914": "Too Many Locals",
    "R0915": "Too Many Statements",
    "R0916": "Too Many Boolean Expressions",
    "R1702": "Too Many Nested Blocks",
    "R1705": "Unnecessary else After Return",
    "R1710": "Inconsistent Return Statements",
    "R1714": "Consider Using In",
    "R1715": "Consider Using Get",
    "R1720": "Unnecessary else After Raise",
    "R1725": "Use super()",
    "R1728": "Consider Using Generator",
    "R1729": "Use a Generator",
    "R1735": "Use Dict Literal",
    "W0104": "Pointless Statement",
    "W0106": "Expression Not Assigned",
    "W0107": "Unnecessary Pass",
    "W0108": "Unnecessary Lambda",
    "W0109": "Duplicate Key In Dict",
    "W0120": "Useless else On Loop",
    "W0122": "Exec Used",
    "W0123": "Eval Used",
    "W0150": "Lost Exception",
    "W0199": "Assert On String Literal",
    "W0201": "Attribute Defined Outside Init",
    "W0211": "Static Method With Self",
    "W0212": "Protected Access",
    "W0221": "Arguments Differ",
    "W0222": "Signature Differs",
    "W0223": "Abstract Method Not Overridden",
    "W0231": "Super Init Not Called",
    "W0233": "Non-Parent Init Called",
    "W0235": "Useless Super Delegation",
    "W0237": "Non-Slot Assignment",
    "W0301": "Unnecessary Semicolon",
    "W0311": "Bad Indentation",
    "W0401": "Wildcard Import",
    "W0404": "Reimported",
    "W0406": "Module Import Self",
    "W0511": "Fixme",
    "W0601": "Global Statement",
    "W0602": "Global Variable Not Assigned",
    "W0603": "Using Global Statement",
    "W0604": "Using Global For Non-Assignment",
    "W0611": "Unused Import",
    "W0612": "Unused Variable",
    "W0613": "Unused Argument",
    "W0614": "Unused Wildcard Import",
    "W0621": "Redefined Outer Name",
    "W0622": "Redefined Builtin",
    "W0631": "Undefined Loop Variable",
    "W0640": "Cell Variable In Loop",
    "W0641": "Possibly Unused Variable",
    "W0642": "Self/Cls Assignment",
    "W0702": "Bare Except",
    "W0703": "Broad Exception",
    "W0705": "Duplicate Except",
    "W0706": "Try Except Raise",
    "W0707": "Raise Missing From",
    "W0711": "Binary Op Exception",
    "W1113": "Keyword Arg Before Var-Positional",
    "W1201": "Logging Not Lazy",
    "W1202": "Logging Format Interpolation",
    "W1203": "Logging f-string Interpolation",
    "W1300": "Bad Format String Key",
    "W1301": "Unused Format String Key",
    "W1302": "Bad Format String",
    "W1303": "Missing Format Arg",
    "W1304": "Unused Format Positional Arg",
    "W1305": "Duplicate String Format Arg",
    "W1401": "Anomalous Backslash In String",
    "W1501": "Bad Open Mode",
    "W1508": "Invalid envvar Default",
    "W1509": "Subprocess Popen preexec_fn",
    "W1510": "Subprocess Run Without Check",
    # ── SQLFluff (L*) ──
    "L001": "Unnecessary Trailing Whitespace",
    "L002": "Mixed Spaces And Tabs",
    "L003": "Indentation Not Consistent",
    "L004": "Indentation Uses Tabs",
    "L005": "Commas Not Followed By Spaces",
    "L006": "Operators Not Surrounded By Spaces",
    "L007": "Operators At End Of Line",
    "L008": "Trailing Commas In SELECT",
    "L009": "Files Must End With Single Newline",
    "L010": "Keywords Not Consistent Case",
    "L011": "Implicit Aliasing",
    "L012": "Implicit Aliasing (Column)",
    "L013": "Column Expression Without Alias",
    "L014": "Identifiers Not Consistent Case",
    "L015": "DISTINCT Used With Parentheses",
    "L016": "Line Too Long",
    "L017": "Function Name Not Followed By Space",
    "L018": "WITH Clause Closing Bracket",
    "L019": "Leading/Trailing Commas",
    "L020": "Table Aliases Duplicate",
    "L021": "Ambiguous Use Of DISTINCT In GROUP BY",
    "L022": "Blank Line After CTE",
    "L023": "Single Whitespace In CTE Definition",
    "L024": "Single Whitespace After USING",
    "L025": "Tables Referenced Without Being Used",
    "L026": "References Non-Existent Table",
    "L027": "References Should Be Qualified In JOIN",
    "L028": "References Should Be Consistent",
    "L029": "Keywords Used As Identifiers",
    "L030": "Function Names Not Consistent Case",
    "L031": "Avoid Aliases In FROM/JOIN",
    "L032": "Prefer COALESCE Over IFNULL/NVL",
    "L033": "UNION With DISTINCT",
    "L034": "Select Wildcards Then Simple",
    "L036": "Select Targets Aligned",
    "L037": "Ambiguous Ordering Direction",
    "L038": "Trailing Commas In SELECT",
    "L039": "Unnecessary Whitespace",
    "L040": "Null/Boolean Inconsistent Case",
    "L041": "SELECT After WITH In Same Line",
    "L042": "Subquery In FROM Should Be CTE",
    "L043": "Unnecessary CASE Statement",
    "L044": "Query Produces Cartesian Product",
    "L045": "Unused CTE",
    "L046": "Jinja Tags Should Have Spacing",
    "L048": "Quoted Literal Should Be Single-Quoted",
    "L049": "IS (NOT) Used With Non-Null",
    "L050": "Files Must Not Begin With Newline",
    "L051": "INNER JOIN Without INNER Keyword",
    "L052": "Statement Must End With Semicolon",
    "L053": "Top-Level Statements Not Separated",
    "L054": "Use Consistent Outer Bracket Spacing",
    "L055": "Use LEFT JOIN Instead Of RIGHT JOIN",
    "L056": "sp_ Prefix In Stored Procedure",
    "L057": "Special Characters In Identifier",
    "L058": "Nested CASE Statement",
    "L059": "Unnecessary Quoted Identifier",
    "L060": "Use COALESCE Instead Of CASE",
    "L061": "Use != Instead Of <>",
    "L062": "Block Statement Alone On Line",
    "L063": "Data Type Identifier Case",
    "L064": "Prefer USING Over ON For Joins",
    "L065": "Set Operators Consistent Wrapping",
    "L066": "Ambiguous Table References In Set Queries",
    "L067": "No Space After Cast",
    # ── Semgrep (common patterns) ──
    "python.lang.security.audit.exec-detected": "Exec/Eval Detected",
    "python.lang.security.deserialization.avoid-pickle": "Pickle Deserialization Risk",
    "python.lang.correctness.useless-comparison": "Useless Comparison",
    "python.lang.security.audit.dangerous-system-call": "Dangerous System Call",
    "python.lang.security.audit.subprocess-shell-true": "Subprocess Shell=True",
    "python.lang.security.audit.insecure-hash": "Insecure Hash Algorithm",
    "python.lang.security.audit.hardcoded-password": "Hardcoded Password",
    "python.lang.correctness.common-mistakes.incorrect-parentheses": "Incorrect Parentheses",
    "python.lang.security.audit.formatted-sql-query": "SQL Injection Risk",
}


def get_rule_name(rule_id: str) -> str:
    """Return human-readable name for a rule code, or the code itself if unknown."""
    if rule_id in RULE_NAMES:
        return RULE_NAMES[rule_id]
    # Try prefix-based fallback for pylint symbol names
    if rule_id.startswith("python."):
        # Semgrep: extract last meaningful segment
        parts = rule_id.rsplit(".", 1)
        return parts[-1].replace("-", " ").replace("_", " ").title()
    return rule_id
