import {
  createContext,
  useContext,
  useEffect,
  useMemo,
  useState,
  type ReactNode,
} from "react";

export type Lang = "en" | "ja";

const STORAGE_KEY = "matrix_lang";

type Dict = Record<string, string>;

const en: Dict = {
  // Sidebar / nav
  "app.subtitle": "Code Quality Platform",
  "nav.home": "Home",
  "nav.overview": "Overview",
  "nav.team": "Team Health",
  "nav.trends": "Trends",
  "nav.security": "Security",
  "nav.admin": "Admin",
  "ui.lightMode": "Light Mode",
  "ui.darkMode": "Dark Mode",
  "ui.language": "Language",

  // Download
  "download.report": "Download Report",
  "download.pdf": "PDF",
  "download.html": "HTML",
  "download.generating": "Generating…",
  "download.failed": "Download failed",
  "download.reportLanguage": "Report language",

  // Welcome
  "welcome.tagline": "Code Quality Assurance Platform",
  "welcome.lede":
    "Comprehensive code quality monitoring for the Autobacs Teradata-to-Databricks migration.",
  "welcome.tools": "Integrated Scanning Tools",
  "welcome.pages": "Dashboard Pages",

  // Overview page
  "overview.title": "Code Quality Overview",
  "overview.subtitle": "Latest scan analysis across all pull requests",
  "overview.gradeDistribution": "Quality Grade Distribution",
  "overview.recentActivity": "Recent Activity",
  "overview.totalPrs": "Total PRs",
  "overview.passing": "Passing",
  "overview.failing": "Failing",
  "overview.mostCommonGrade": "Most common grade",

  // Team page
  "team.title": "Team Health",
  "team.subtitle": "Contributor metrics and team-wide quality trends",
  "team.totalScans": "Total Scans",
  "team.passRate": "Pass Rate",
  "team.failingPrs": "Failing PRs",
  "team.activeAuthors": "Active Authors",
  "team.contributors": "Contributors",
  "team.recentScans": "Recent Scans",

  // Trends page
  "trends.title": "Quality Trends",
  "trends.subtitle": "Track code quality metrics across {n} scans",
  "trends.metricComparison": "Metric Comparison",

  // Security page
  "security.title": "Security Overview",
  "security.subtitle":
    "Vulnerability analysis, secret detection, and OWASP categorization",
  "security.totalVulns": "Total Vulnerabilities",
  "security.totalSecrets": "Total Secrets",
  "security.highSeverity": "High Severity",
  "security.owaspCategories": "OWASP Categories",
  "security.banditDistribution": "Bandit Severity Distribution",
  "security.owaspDetails": "OWASP Category Details",
  "security.allFindings": "All Security Findings",

  // PR detail
  "pr.backToOverview": "Back to overview",
  "pr.viewing": "Currently viewing",
  "pr.switchPr": "Switch PR",
  "pr.technicalDebt": "Technical Debt",
  "pr.remediation": "Remediation",
  "pr.development": "Development",
  "pr.loc": "LOC",
  "pr.bugsPerKloc": "Bugs/kLOC",
  "pr.vulnsPerKloc": "Vulns/kLOC",
  "pr.issuesByTool": "Issues by Tool",
  "pr.banditSecurity": "Bandit Security",
  "pr.notebookVsSource": "Notebook vs Python Source",

  // Findings sections
  "findings.ruff": "Ruff Findings",
  "findings.bandit": "Bandit Security Findings",
  "findings.semgrep": "Semgrep Findings",
  "findings.gitleaks": "Secret Detection (Gitleaks)",
  "findings.jscpd": "Code Duplication (JSCPD)",
  "findings.aiReview": "AI Code Review",

  // Tables
  "table.pr": "PR",
  "table.author": "Author",
  "table.branch": "Branch",
  "table.status": "Status",
  "table.grade": "Grade",
  "table.bugs": "Bugs",
  "table.security": "Security",
  "table.date": "Date",
  "table.rule": "Rule",
  "table.severity": "Severity",
  "table.file": "File",
  "table.line": "Line",
  "table.message": "Message",
  "table.source": "Source",
  "table.owasp": "OWASP",
  "table.passCount": "Pass",
  "table.failCount": "Fail",
  "table.prCount": "PRs",

  // Status / grade / severity
  "status.pass": "PASS",
  "status.fail": "FAIL",
  "grade.A": "Excellent",
  "grade.B": "Good",
  "grade.C": "Fair",
  "grade.D": "Poor",
  "grade.E": "Critical",
  "severity.high": "High",
  "severity.medium": "Medium",
  "severity.low": "Low",
  "severity.error": "Error",
  "severity.warning": "Warning",

  // Report shell
  "report.title": "MATRIX — Code Quality Report",
  "report.generated": "Generated",
  "report.section.overview": "Overview",
  "report.section.trends": "Trends",
  "report.section.team": "Team Health",
  "report.section.security": "Security",
  "report.section.prDetail": "PR Detail",
  "report.section.benchmarks": "Industry Benchmarks",
  "report.section.scanners": "Scanner Stack",
  "report.section.prSummary": "Recent PR Summary",
  "report.footer": "Generated by MATRIX Code Quality Platform",
  "report.page": "Page",
  "report.of": "of",
  "report.toc": "Contents",
  "report.qualityGrade": "Quality Grade",
  "report.scansIncluded": "Scans included",
  "report.tooMany": "+{n} more — see dashboard",
  "report.trends.latest": "Latest",
  "report.trends.changeVsPrev": "Change vs prev",
  "report.trends.deltaNote":
    "\"Change vs prev\" shows the difference between the latest scan and the previous scan (latest − previous). Positive means the metric increased; negative means it decreased.",

  // New report content
  "report.gradeDistExplainer":
    "Counts of PRs by quality letter grade (A best, E worst) across the most recent {n} scans. Each grade is a weighted score across 6 dimensions; see the dashboard for the full breakdown.",
  "report.recentN": "Recent {n} PRs",
  "report.scanners.intro":
    "The platform runs the scanners below on every PR. Each tool covers a specific quality dimension — linting, security, bugs, secrets, and duplication.",
  "report.benchmarks.intro":
    "Industry benchmarks below are commonly cited norms (SonarQube SQALE model, OWASP guidance, peer-reviewed empirical studies). 'Our threshold' is what the platform flags as warning/danger via admin config.",
  "report.benchmarks.metric": "Metric",
  "report.benchmarks.tool": "Tool",
  "report.benchmarks.ourThreshold": "Our threshold",
  "report.benchmarks.industry": "Industry benchmark",
  "report.benchmarks.current": "Current value",
  "report.benchmarks.statusGood": "Good",
  "report.benchmarks.statusWarning": "Warning",
  "report.benchmarks.statusDanger": "Danger",
  "report.prSummary.intro":
    "One-line summary per recent PR. For full per-tool findings, download the per-PR report from the PR detail page.",
};

const ja: Dict = {
  // Sidebar / nav
  "app.subtitle": "コード品質プラットフォーム",
  "nav.home": "ホーム",
  "nav.overview": "概要",
  "nav.team": "チーム健全性",
  "nav.trends": "トレンド",
  "nav.security": "セキュリティ",
  "nav.admin": "管理",
  "ui.lightMode": "ライトモード",
  "ui.darkMode": "ダークモード",
  "ui.language": "言語",

  // Download
  "download.report": "レポートをダウンロード",
  "download.pdf": "PDF",
  "download.html": "HTML",
  "download.generating": "生成中…",
  "download.failed": "ダウンロード失敗",
  "download.reportLanguage": "レポート言語",

  // Welcome
  "welcome.tagline": "コード品質保証プラットフォーム",
  "welcome.lede":
    "Autobacs の Teradata から Databricks への移行に向けた包括的なコード品質モニタリング。",
  "welcome.tools": "統合スキャンツール",
  "welcome.pages": "ダッシュボードページ",

  // Overview page
  "overview.title": "コード品質の概要",
  "overview.subtitle": "全プルリクエストにおける最新スキャン分析",
  "overview.gradeDistribution": "品質グレード分布",
  "overview.recentActivity": "最近のアクティビティ",
  "overview.totalPrs": "PR 合計",
  "overview.passing": "合格",
  "overview.failing": "不合格",
  "overview.mostCommonGrade": "最も多いグレード",

  // Team page
  "team.title": "チーム健全性",
  "team.subtitle": "コントリビューター指標とチーム全体の品質トレンド",
  "team.totalScans": "スキャン合計",
  "team.passRate": "合格率",
  "team.failingPrs": "不合格 PR",
  "team.activeAuthors": "アクティブ作者",
  "team.contributors": "コントリビューター",
  "team.recentScans": "最近のスキャン",

  // Trends page
  "trends.title": "品質トレンド",
  "trends.subtitle": "{n} 件のスキャンにわたるコード品質指標を追跡",
  "trends.metricComparison": "指標の比較",

  // Security page
  "security.title": "セキュリティ概要",
  "security.subtitle":
    "脆弱性分析、シークレット検出、および OWASP カテゴリ分類",
  "security.totalVulns": "脆弱性合計",
  "security.totalSecrets": "シークレット合計",
  "security.highSeverity": "高深刻度",
  "security.owaspCategories": "OWASP カテゴリ",
  "security.banditDistribution": "Bandit 深刻度分布",
  "security.owaspDetails": "OWASP カテゴリ詳細",
  "security.allFindings": "全セキュリティ検出結果",

  // PR detail
  "pr.backToOverview": "概要に戻る",
  "pr.viewing": "現在表示中",
  "pr.switchPr": "PR を切り替え",
  "pr.technicalDebt": "技術的負債",
  "pr.remediation": "修復時間",
  "pr.development": "開発時間",
  "pr.loc": "コード行数",
  "pr.bugsPerKloc": "バグ/kLOC",
  "pr.vulnsPerKloc": "脆弱性/kLOC",
  "pr.issuesByTool": "ツール別の問題",
  "pr.banditSecurity": "Bandit セキュリティ",
  "pr.notebookVsSource": "ノートブック対 Python ソース",

  // Findings sections
  "findings.ruff": "Ruff 検出結果",
  "findings.bandit": "Bandit セキュリティ検出結果",
  "findings.semgrep": "Semgrep 検出結果",
  "findings.gitleaks": "シークレット検出 (Gitleaks)",
  "findings.jscpd": "コード重複 (JSCPD)",
  "findings.aiReview": "AI コードレビュー",

  // Tables
  "table.pr": "PR",
  "table.author": "作者",
  "table.branch": "ブランチ",
  "table.status": "ステータス",
  "table.grade": "グレード",
  "table.bugs": "バグ",
  "table.security": "セキュリティ",
  "table.date": "日付",
  "table.rule": "ルール",
  "table.severity": "深刻度",
  "table.file": "ファイル",
  "table.line": "行",
  "table.message": "メッセージ",
  "table.source": "ソース",
  "table.owasp": "OWASP",
  "table.passCount": "合格",
  "table.failCount": "不合格",
  "table.prCount": "PR 数",

  // Status / grade / severity
  "status.pass": "合格",
  "status.fail": "不合格",
  "grade.A": "優秀",
  "grade.B": "良好",
  "grade.C": "普通",
  "grade.D": "不良",
  "grade.E": "重大",
  "severity.high": "高",
  "severity.medium": "中",
  "severity.low": "低",
  "severity.error": "エラー",
  "severity.warning": "警告",

  // Report shell
  "report.title": "MATRIX — コード品質レポート",
  "report.generated": "作成日時",
  "report.section.overview": "概要",
  "report.section.trends": "トレンド",
  "report.section.team": "チーム健全性",
  "report.section.security": "セキュリティ",
  "report.section.prDetail": "PR 詳細",
  "report.section.benchmarks": "業界ベンチマーク",
  "report.section.scanners": "スキャナー構成",
  "report.section.prSummary": "最近の PR サマリー",
  "report.footer": "MATRIX コード品質プラットフォームにより作成",
  "report.page": "ページ",
  "report.of": "/",
  "report.toc": "目次",
  "report.qualityGrade": "品質グレード",
  "report.scansIncluded": "対象スキャン数",
  "report.tooMany": "+{n} 件以上 — ダッシュボードを参照",
  "report.trends.latest": "最新値",
  "report.trends.changeVsPrev": "前回比",
  "report.trends.deltaNote":
    "「前回比」は最新スキャンと前回スキャンの差分を表します（最新 − 前回）。正の値は増加、負の値は減少を意味します。",

  // New report content
  "report.gradeDistExplainer":
    "最近 {n} 件のスキャンを対象に、品質レターグレード (A が最良、E が最悪) ごとの PR 数を集計しています。各グレードは 6 つの観点による加重スコアで決まります。詳細はダッシュボードを参照してください。",
  "report.recentN": "最近の {n} 件の PR",
  "report.scanners.intro":
    "PR ごとに以下のスキャナーが実行されます。各ツールは品質の特定領域 (リンティング、セキュリティ、バグ、シークレット、重複) を担当します。",
  "report.benchmarks.intro":
    "以下の業界ベンチマークは、SonarQube の SQALE モデル、OWASP ガイダンス、査読済みの実証研究などで一般的に参照される値です。「自社しきい値」は管理者設定により warning / danger として扱う値です。",
  "report.benchmarks.metric": "指標",
  "report.benchmarks.tool": "ツール",
  "report.benchmarks.ourThreshold": "自社しきい値",
  "report.benchmarks.industry": "業界ベンチマーク",
  "report.benchmarks.current": "現在値",
  "report.benchmarks.statusGood": "良好",
  "report.benchmarks.statusWarning": "警告",
  "report.benchmarks.statusDanger": "要対応",
  "report.prSummary.intro":
    "最近の PR を 1 行ずつ要約しています。ツール別の検出結果の詳細は、PR 詳細ページから個別の PR レポートをダウンロードしてください。",
};

const DICTS: Record<Lang, Dict> = { en, ja };

function format(template: string, vars?: Record<string, string | number>): string {
  if (!vars) return template;
  return template.replace(/\{(\w+)\}/g, (_, k) =>
    k in vars ? String(vars[k]) : `{${k}}`,
  );
}

export function translate(
  lang: Lang,
  key: string,
  vars?: Record<string, string | number>,
): string {
  const value = DICTS[lang]?.[key] ?? DICTS.en[key] ?? key;
  return format(value, vars);
}

interface I18nContextValue {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string, vars?: Record<string, string | number>) => string;
}

const I18nContext = createContext<I18nContextValue | null>(null);

export function I18nProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    if (typeof window === "undefined") return "en";
    const stored = window.localStorage.getItem(STORAGE_KEY);
    return stored === "ja" ? "ja" : "en";
  });

  useEffect(() => {
    if (typeof document !== "undefined") {
      document.documentElement.lang = lang;
    }
  }, [lang]);

  const value = useMemo<I18nContextValue>(
    () => ({
      lang,
      setLang: (l) => {
        setLangState(l);
        if (typeof window !== "undefined") {
          window.localStorage.setItem(STORAGE_KEY, l);
        }
      },
      t: (key, vars) => translate(lang, key, vars),
    }),
    [lang],
  );

  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}

export function useI18n(): I18nContextValue {
  const ctx = useContext(I18nContext);
  if (!ctx) throw new Error("useI18n must be used inside <I18nProvider>");
  return ctx;
}

export function useT() {
  return useI18n().t;
}

export function getStoredLang(): Lang {
  if (typeof window === "undefined") return "en";
  return window.localStorage.getItem(STORAGE_KEY) === "ja" ? "ja" : "en";
}
